### ISSUE TITLE
ClientAuth: refresh_tokens() doesn't work

### ISSUE THREAD

**Issue by rclsilver** [jabesq/netatmo-api-python#114]
Hi,

I'm using 4.0.0 and ClientAuth. When tokens are expired, i've the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/netatmo2influxdb", line 73, in update
    weather = WeatherStationData(auth)
  File "/usr/local/lib/python3.7/site-packages/pyatmo/weather_station.py", line 30, in __init__
    resp = self.auth.post_request(url=self.url_req)
  File "/usr/local/lib/python3.7/site-packages/pyatmo/auth.py", line 156, in post_request
    resp = query(url, params, timeout, 3)
  File "/usr/local/lib/python3.7/site-packages/pyatmo/auth.py", line 150, in query
    self._oauth.token = self.refresh_tokens()
  File "/usr/local/lib/python3.7/site-packages/pyatmo/auth.py", line 96, in refresh_tokens
    token = self._oauth.refresh_token(AUTH_REQ, **self.extra)
AttributeError: 'ClientAuth' object has no attribute 'extra'
```

My auth object is created like that:

```python
    try:
        auth = ClientAuth(
            client_id=os.getenv('NETATMO_CLIENT_ID'),
            client_secret=os.getenv('NETATMO_CLIENT_SECRET'),
            username=os.getenv('NETATMO_USERNAME'),
            password=os.getenv('NETATMO_PASSWORD'),
            scope='read_station',
        )
    except HTTPError as e:
        logging.error('Unable to connect to Netatmo API')
        logging.exception(e)
        sys.exit(1)
```

Full project code: https://github.com/rclsilver/netatmo2influxdb/blob/master/netatmo2influxdb.py

**Comment by cgtobi** [comment]
Hi Thomas,

could you please try the following local:

```python
    try:
        auth = ClientAuth(
            client_id=os.getenv('NETATMO_CLIENT_ID'),
            client_secret=os.getenv('NETATMO_CLIENT_SECRET'),
            username=os.getenv('NETATMO_USERNAME'),
            password=os.getenv('NETATMO_PASSWORD'),
        )
        auth.extra = {"client_id": os.getenv('NETATMO_CLIENT_ID'), "client_secret": os.getenv('NETATMO_CLIENT_SECRET')}
    except HTTPError as e:
        logging.error('Unable to connect to Netatmo API')
        logging.exception(e)
        sys.exit(1)
```

Best regards,
Tobias

**Comment by rclsilver** [comment]
This should work, maybe you could define extra field in constructor?

**Comment by cgtobi** [comment]
Sure, that's what I had in mind. I just wanted to ask you to verify the fix before we'd release it.

Also, you can drop the scope argument since that is the default.

**Comment by cgtobi** [comment]
Hi @rclsilver, did you already had a chance to test this patch/fix?

**Comment by cgtobi** [comment]
Hi @rclsilver, I've opened a PR which should fix that issue properly. I'd really appreciate if you could give that a spin.

**Comment by Mikado8231** [comment]
Hi Tobias, I have the same issue than rclsilver.
I put you fix on my home installation. I will give you a feedback in 1 or 2 days if it's OK.

**Comment by cgtobi** [comment]
Thanks, any feedback is greatly appreciated.

**Comment by Mikado8231** [comment]
After 2 days, all work fine on my side @cgtobi good job :+1:

**Comment by cgtobi** [comment]
Thank you very much @Mikado8231 for the feedback.
