### ISSUE TITLE
Sensor broken on 116.1

### ISSUE THREAD

**Issue by RenfoJu1** [jabesq/netatmo-api-python#119]
Log Details (ERROR)
Logger: homeassistant.components.sensor
Source: components/netatmo/sensor.py:252
Integration: Sensor (documentation, issues)
First occurred: 6:27:17 AM (1 occurrences)
Last logged: 6:27:17 AM

Error while setting up netatmo platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/src/homeassistant/homeassistant/components/netatmo/sensor.py", line 159, in async_setup_entry
    async_add_entities(await find_entities(data_class_name), True)
  File "/usr/src/homeassistant/homeassistant/components/netatmo/sensor.py", line 150, in find_entities
    NetatmoSensor(data_handler, data_class_name, module, condition)
  File "/usr/src/homeassistant/homeassistant/components/netatmo/sensor.py", line 252, in __init__
    f"{MANUFACTURER} {self._device_name} {SENSOR_TYPES[sensor_type][0]}"
KeyError: 'temp_trend'

**Comment by cgtobi** [comment]
This is a Home Assistant issue, not pyatmo.
