### ISSUE TITLE
Rain Sensors Not Showing

### ISSUE THREAD

**Issue by stringy92** [jabesq/netatmo-api-python#21]
Rain_Sum_1 & Rain_Sum_24 are not showing using the current configuration setup on Home Assistant. When sensors are stated the following errors appear

```
`Error while setting up platform netatmo
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/sensor/netatmo.py", line 80, in setup_platform
    if module_name not in data.get_module_names():
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/sensor/netatmo.py", line 304, in get_module_names
    self.update()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/sensor/netatmo.py", line 333, in update
    for module in self.data:
TypeError: 'NoneType' object is not iterable``
```

**Comment by magma1447** [comment]
This pull requests solves it. You can edit your current library in Home Assistant and patch it in yourself meanwhile.
https://github.com/jabesq/netatmo-api-python/pull/44

**Comment by cgtobi** [comment]
Is this still an issue with 1.11?
