### ISSUE TITLE
'CameraData' object has no attribute 'default_home'

### ISSUE THREAD

**Issue by lasote** [jabesq/netatmo-api-python#29]
I have no camera, so I bet `self.default_home` is never assigned. It fails with homeassistant project.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/binary_sensor/netatmo.py", line 73, in setup_platform
    if not data.get_camera_names():
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/netatmo.py", line 82, in get_camera_names
    self.update()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/util/__init__.py", line 324, in wrapper
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/netatmo.py", line 113, in update
    self.camera_data = pyatmo.CameraData(self.auth, size=100)
  File "/data/hass_conf/deps/lib/python3.6/site-packages/smart_home/Camera.py", line 81, in __init__
    self.default_camera = list(self.cameras[self.default_home].values())[0]
AttributeError: 'CameraData' object has no attribute 'default_home'
```

**Comment by shanbs** [comment]
This has been fixed by PR #27. A re-publish of `pyatmo` library of 1.5 (or 1.6) is required.
